# Generated by Django 4.0.3 on 2022-04-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_offer_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.CharField(max_length=255)),
                ('brand', models.TextField(max_length=25)),
                ('branch', models.TextField(max_length=20)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
