# Generated by Django 4.0.3 on 2022-04-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='offers',
            new_name='offer',
        ),
    ]
